parameters:
- name: hugoVersion
  displayName: Hugo Version
  type: string
  default: latest
# - name: syncGitHub
#   displayName: Synchronize repository to GitHub
#   type: boolean
#   default: true


trigger:
  branches:
    include:
    - develop
    - main
  paths:
    exclude:
    - .azuredevops/**
    - .github/**

# resources:
#   repositories:
#     - repository: bca-cicd
#       type: git
#       name: bca-cicd

stages:
- stage: Initialization
  displayName: Initialization
  jobs:
  - job: Initialize
    displayName: Initialize Build
    steps:
    - checkout: none
    - powershell: Write-Host "##vso[build.updatebuildnumber]$(Build.DefinitionName)-$(Build.BuildNumber)"
      displayName: Set Build Number
- stage: Build
  displayName: Build
  pool:
    name: Azure Pipelines
    vmImage: windows-latest
  jobs:
  - job: Hugo
    displayName: Build Hugo Website
    steps:
    - task: giuliovdev.hugo-extension.hugo-build-task.HugoTask@1
      displayName: 'Hugo Generate'
      inputs:
        source: $(Build.Repository.LocalPath)/src/
        destination: $(Build.Repository.LocalPath)/src/public
        hugoVersion: ${{ parameters.hugoVersion }}
        buildDrafts: true
    - task: CopyFiles@2
      displayName: 'Copy Sources to Staging'
      inputs:
        SourceFolder: $(Build.Repository.LocalPath)/src
        Contents: |
          public/**
          wrangler.toml
          !**\.gitignore
        TargetFolder: '$(Build.StagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true
    - powershell: Get-ChildItem "$(Build.StagingDirectory)" -Recurse  
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Build.StagingDirectory)'
        artifact: '$(Build.BuildNumber)'
      condition: |
        and(
            succeeded(),
            ne(variables['Build.Reason'], 'PullRequest'),
            eq(variables['Build.SourceBranchName'], 'main')
        )

# - template: azuredevops/pipelines/pipeline-sync-repo.yml@bca-cicd
#   parameters:
#     syncGitHub: ${{ parameters.syncGitHub }}