trigger:
- none

resources:
  pipelines:
  - pipeline: Build
    source: Build\baptistecabrera.com
    trigger: 
      branches:
      - main

variables:
- group: CloudFlare
- name: artifactPath
  value: $(Pipeline.Workspace)/Build/$(resources.pipeline.Build.runName)

stages:
- stage: Initialization
  displayName: Initialization
  jobs:
  - job: Initialize
    displayName: Initialize Release
    steps:
    - checkout: none
    - powershell: Write-Host "##vso[build.updatebuildnumber]$(Build.DefinitionName)-$(Build.BuildNumber)"
      displayName: Set Build Number
- stage: Release
  displayName: Release
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  jobs:
  - job: Release
    displayName: Release Website
    steps:
    - checkout: none
    - script: npm i @cloudflare/wrangler
      displayName: Install Wrangler
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        source: specific
        project: '$(resources.pipeline.Build.projectID)'
        pipeline: '$(resources.pipeline.Build.pipelineID)'
        preferTriggeringPipeline: true
        runVersion: specific
        runId: '$(resources.pipeline.Build.runID)'
        artifact: '$(resources.pipeline.Build.runName)'
        path: '$(artifactPath)'
    - powershell: Get-ChildItem $(Pipeline.Workspace) -Recurse
    - powershell: Get-ChildItem $(artifactPath) -Recurse