trigger:
- none

resources:
  pipelines:
  - pipeline: Build
    source: Build\baptistecabrera.com
    trigger: 
      branches:
      - main

variables:
- group: CloudFlare
- name: artifactPath
  value: $(Pipeline.Workspace)/Build/$(resources.pipeline.Build.runName)
- name: compatibilityDate
  value: $[ format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime) ]

stages:
- stage: Initialization
  displayName: Initialization
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  jobs:
  - job: Initialize
    displayName: Initialize Release
    steps:
    - checkout: none
    - powershell: Write-Host "##vso[build.updatebuildnumber]$(Build.DefinitionName)-$(Build.BuildNumber)"
      displayName: Set Build Number
    - script: echo $(compatibilityDate)
      displayName: Set Compatibility Date
- stage: Release
  displayName: Release
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
    demands: npm
  jobs:
  - job: Release
    displayName: Release Website
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        source: specific
        project: '$(resources.pipeline.Build.projectID)'
        pipeline: '$(resources.pipeline.Build.pipelineID)'
        preferTriggeringPipeline: true
        runVersion: specific
        runId: '$(resources.pipeline.Build.runID)'
        artifact: '$(resources.pipeline.Build.runName)'
        path: '$(artifactPath)'
    - script: npm install -g wrangler
      displayName: Install Wrangler
      workingDirectory: $(artifactPath)
    - script: npx wrangler deploy --compatibility-date '$(compatibilityDate)''
      displayName: Deploy Website
      workingDirectory: $(artifactPath)
      env:
        CLOUDFLARE_ACCOUNT_ID: $(CloudFlareAccountId)
        CLOUDFLARE_API_TOKEN: $(CloudFlareApiToken)
