parameters:
- name: syncGitHub
  displayName: Sync with GitHub
  type: boolean
  default: true

trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: windows-latest

resources:
  pipelines:
  - pipeline: Release
    source: Release\baptistecabrera.com
    trigger: 
      branches:
      - main
  repositories:
  - repository: bca-cicd
    type: git
    name: bca-cicd

variables:
- template: azuredevops/pipelines/variables/all.yml@bca-cicd

stages: 
- template: azuredevops/pipelines/pipeline-sync-repo.yml@bca-cicd
  parameters:
    syncGitHub: ${{ parameters.syncGitHub }}