parameters:
- name: syncGitHub
  displayName: Sync with GitHub
  type: boolean
  default: true

trigger:
- none

resources:
  pipelines:
  - pipeline: Release
    source: Release\baptistecabrera.com
    trigger: 
      branches:
      - main
  repositories:
  - repository: bca-cicd
    type: git
    name: bca-cicd

variables:
- template: pipelines/azuredevops/variables/all.yml@build-tools

stages: 
- template: pipelines/azuredevops/pipeline-sync-repo.yml@build-tools
  parameters:
    syncGitHub: ${{ parameters.syncGitHub }}