baseURL = "https://www.baptistecabrera.com/"
languageCode = "en-us"
title = "Baptiste Cabrera"
theme = "baptiste2021"
enableRobotsTXT = true
disableHugoGeneratorInject = true
[markup.goldmark.renderer]
unsafe= true
enableEmoji = true
hrefTargetBlank = true
